=== MarcinKulwicki/OrdersCSVXML/XML/order.dtd
<!ELEMENT requests (request)+>
        <!ELEMENT request (clientId , requestId , name , quantity , price)>
        <!ELEMENT clientId (#PCDATA)*>
        <!ELEMENT requestId (#PCDATA)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT quantity (#PCDATA)>
        <!ELEMENT price (#PCDATA)>

=== MarcinKulwicki/OrdersCSVXML/XML/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE requests SYSTEM "./order.dtd">
<requests>
    <request>
        <clientId>1</clientId>
        <requestId>5</requestId>
        <name>Bułka</name>
        <quantity>2</quantity>
        <price>11.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>5</requestId>
        <name>Bułka</name>
        <quantity>2</quantity>
        <price>11.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>5</requestId>
        <name>Bułka</name>
        <quantity>2</quantity>
        <price>11.0</price>
    </request>
</requests>

=== MarcinKulwicki/OrdersCSVXML/XML/f_AllOrdersById.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE requests SYSTEM "./order.dtd">
<requests>
    <request>
        <clientId>6</clientId>
        <requestId>3</requestId>
        <name>Mintaj</name>
        <quantity>2</quantity>
        <price>52.6</price>
    </request>
    <request>
        <clientId>6</clientId>
        <requestId>5</requestId>
        <name>Dorsz</name>
        <quantity>8</quantity>
        <price>13.8</price>
    </request>
</requests>

=== MarcinKulwicki/OrdersCSVXML/XML/e_AllOrders.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE requests SYSTEM "./order.dtd">
<requests>
    <request>
        <clientId>1</clientId>
        <requestId>1</requestId>
        <name>Bułka</name>
        <quantity>1</quantity>
        <price>10.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>1</requestId>
        <name>Chleb</name>
        <quantity>2</quantity>
        <price>15.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>2</requestId>
        <name>Chleb</name>
        <quantity>5</quantity>
        <price>15.0</price>
    </request>
    <request>
        <clientId>2</clientId>
        <requestId>1</requestId>
        <name>Chleb</name>
        <quantity>1</quantity>
        <price>10.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>1</requestId>
        <name>Bułka</name>
        <quantity>1</quantity>
        <price>10.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>2</requestId>
        <name>Chleb</name>
        <quantity>2</quantity>
        <price>15.0</price>
    </request>
    <request>
        <clientId>1</clientId>
        <requestId>2</requestId>
        <name>Chleb</name>
        <quantity>5</quantity>
        <price>15.0</price>
    </request>
    <request>
        <clientId>2</clientId>
        <requestId>1</requestId>
        <name>Chleb</name>
        <quantity>1</quantity>
        <price>10.0</price>
    </request>
    <request>
        <clientId>4</clientId>
        <requestId>2</requestId>
        <name>Łosoś</name>
        <quantity>12</quantity>
        <price>352.2</price>
    </request>
    <request>
        <clientId>5</clientId>
        <requestId>1</requestId>
        <name>Makrela</name>
        <quantity>1</quantity>
        <price>32.26</price>
    </request>
    <request>
        <clientId>6</clientId>
        <requestId>3</requestId>
        <name>Mintaj</name>
        <quantity>2</quantity>
        <price>52.6</price>
    </request>
    <request>
        <clientId>6</clientId>
        <requestId>5</requestId>
        <name>Dorsz</name>
        <quantity>8</quantity>
        <price>13.8</price>
    </request>
    <request>
        <clientId>7</clientId>
        <requestId>1</requestId>
        <name>Korniszon</name>
        <quantity>100</quantity>
        <price>100.2</price>
    </request>
</requests>
